# SPDX-FileCopyrightText: 2012-2026 Open Assessment Technologies S.A.
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-TAO-Commercial-License

files:
  - source: /src/locale/messages.pot
    translation: /%original_path%/%locale%/%file_name%.po

"pull_request_title": "Update translations from Crowdin"
"pull_request_description": "This pull request updates translations from Crowdin"
"pull_request_labels": ["l10n", "translations"]
"pull_request_assignees": ["oat-github-bot", "pribi"]
"pull_request_reviewers": ["oat-github-bot", "yukipastelcat", "ViktoriaKh-oat"]

"commit_message": "chore: sync latest translations from Crowdin"
